---
language: python
python:
    - "2.7"

env:
    global:
        - SSH_RSYNC="ssh -oIdentityFile=~/.ssh/id_nethbot -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null"
        - BUILD_DIR=administrator-manual/it
        - TARGET_DIR=${TRAVIS_PULL_REQUEST_BRANCH:-${TRAVIS_TAG:-${TRAVIS_BRANCH}}}

before_install:
    - openssl aes-256-cbc -K $encrypted_07150588eeca_key -iv $encrypted_07150588eeca_iv -in id_nethbot_nethmonitor.enc -out ~/.ssh/id_nethbot -d
    - chmod -c 600 ~/.ssh/id_nethbot

install:
    - pip install sphinx==1.7.4
    - pip install -r ${BUILD_DIR}/requirements.txt

script:
    - pushd ${BUILD_DIR}/
    - sphinx-build                -b html -d _build/doctrees/it   . _build/webroot/it/${TARGET_DIR}
    - popd

deploy:
    provider: script
    skip_cleanup: true
    script: rsync -ai --no-super --delete-after -e "${SSH_RSYNC}" ${BUILD_DIR}/_build/webroot/* nethbot@docs1.nethserver.com:.
    on:
        all_branches: true
